import SideTableLayout from "@/components/layout/side-table";

import type { LayoutProps } from "@/types/global";
import React from "react";

import { Metadata } from "next";
import EmployeeSideBarTable from "@/features/payroll/employee/SidebarTable";
export const metadata: Metadata = {
  title: "Employee",
  description: "Generated by create next app",
};

function layout({ children }: LayoutProps) {
  return (
    <SideTableLayout
      Sidebar={<EmployeeSideBarTable pushUrl="/v1/payroll/payslips/create" />}
      Main={children}
    />
  );
}

export default layout;
