import SideTableLayout from "@/components/layout/side-table";

import OrdersMiniTable from "@/features/orders/mini-table/MiniTable";
import type { LayoutProps } from "@/types/global";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "RBS | Orders",
  description: "Generated by create next app",
};
function OrderSidebarLayout({ children }: LayoutProps) {
  return <SideTableLayout Main={children} Sidebar={<OrdersMiniTable />} />;
}

export default OrderSidebarLayout;
