import { LayoutProps } from "@/types/global";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Embro Art",
  description: "Generated by create next app",
};

function Layout({ children }: LayoutProps) {
  return children;
}

export default Layout;
