import { LayoutProps } from "@/types/global";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "RBS | Customers",
  description: "Generated by create next app",
};

function CustomerLayout({ children }: LayoutProps) {
  return children;
}

export default CustomerLayout;
