import { LayoutProps } from "@/types/global";
import { Metadata } from "next";
import { Suspense } from "react";
export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

function Layout({ children }: LayoutProps) {
  return <Suspense fallback={<div>loading...</div>}>{children}</Suspense>;
}

export default Layout;
