import SideTableLayout from "@/components/layout/side-table";
import ChartOfAccounts from "@/features/chart-of-accounts";

import type { LayoutProps } from "@/types/global";
import React from "react";

import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Accounts",
  description: "Generated by create next app",
};

function layout({ children }: LayoutProps) {
  return <SideTableLayout Sidebar={<ChartOfAccounts />} Main={children} />;
}

export default layout;
